import { TraffixAlert } from "@/types/alerts";

export const MOCK_ALERTS: TraffixAlert[] = [
  {
    id: "alt-001",
    severity: "critical",
    category: "accident",
    title: "Multi-vehicle accident — Anna Salai Teynampet",
    description: "3-vehicle collision detected at Teynampet Junction (Node 14). Lane 2 fully blocked. XGBoost risk score: 0.93.",
    source: "Optical Camera CAM-02",
    location: "Anna Salai, Teynampet Junction",
    timestamp: "17:51:00",
    acknowledged: false,
    dismissed: false,
  },
  {
    id: "alt-002",
    severity: "critical",
    category: "emergency",
    title: "Ambulance A-07 dispatched — Emergency corridor active",
    description: "Unit A-07 responding to ACC-101. Green wave active on 2/4 corridor junctions. ETA 3 min.",
    source: "Dispatch Command",
    location: "Nungambakkam → Teynampet → Apollo Hospital",
    timestamp: "17:51:22",
    acknowledged: true,
    dismissed: false,
  },
  {
    id: "alt-003",
    severity: "warning",
    category: "routing",
    title: "Route 1 blocked — Dynamic reroute applied",
    description: "Shortest path via Anna Salai (Teynampet) blocked. System rerouted 1,240 vehicles via Mount Flyover Bypass (Route 2). Avg delay: +2.1 min.",
    source: "Route Optimization Engine",
    location: "Anna Salai Corridor",
    timestamp: "17:51:35",
    acknowledged: false,
    dismissed: false,
  },
  {
    id: "alt-004",
    severity: "warning",
    category: "signal",
    title: "Junction queue overflow — Guindy Signal 04",
    description: "Queue length exceeded 400 m at Guindy Inner Ring Road (Signal 04). AI adaptive phase recommendation: extend green by 22s.",
    source: "Signal Management AI",
    location: "Guindy Inner Ring Road, Signal 04",
    timestamp: "17:52:10",
    acknowledged: false,
    dismissed: false,
  },
  {
    id: "alt-005",
    severity: "info",
    category: "prediction",
    title: "Peak congestion window approaching — 17:00–19:00",
    description: "XGBoost v15 forecasts occupancy >80% on Anna Salai and Mount Rd within 12 minutes. Pre-emptive signal phase adjustment recommended.",
    source: "XGBoost v15 Prediction Engine",
    location: "Anna Salai · Mount Rd · Guindy Ring",
    timestamp: "17:48:00",
    acknowledged: false,
    dismissed: false,
  },
  {
    id: "alt-006",
    severity: "info",
    category: "iot",
    title: "Camera CAM-01 — Data lag detected",
    description: "Optical camera CAM-01 at Nungambakkam High Rd reporting 4.2 s data lag. Health index: 87%. Investigating feed.",
    source: "IoT Monitoring System",
    location: "Nungambakkam High Rd",
    timestamp: "17:49:15",
    acknowledged: true,
    dismissed: false,
  },
  {
    id: "alt-007",
    severity: "success",
    category: "emergency",
    title: "Rescue complete — Patient delivered to Apollo Hospital",
    description: "Ambulance A-07 successfully delivered patient to Apollo Hospital (Greams Rd). Emergency corridor deactivated. Total response time: 3 min 42 s.",
    source: "Emergency Command",
    location: "Apollo Hospital, Greams Rd",
    timestamp: "17:54:42",
    acknowledged: true,
    dismissed: false,
  },
  {
    id: "alt-008",
    severity: "info",
    category: "system",
    title: "SUMO TraCI simulation — Step 3,600 reached (1-hr epoch complete)",
    description: "SUMO v1.18.0 completed full 1-hour epoch on Anna Salai OSM network. Results saved. Ready for next scenario.",
    source: "SUMO Engine",
    location: "Anna Salai OSM Network",
    timestamp: "17:55:00",
    acknowledged: false,
    dismissed: false,
  },
];
